---
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this is a test"
          exit 1
  test2:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this is test 2"
          exit 1
  postError:
    runs-on: ubuntu-latest
    needs:
      - test
      - test2
    if: ${{ failure() }}
    steps:
      - run: |
          echo "ran after failure"
